spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  flyway:
#    migrate-at-start: true
#    baseline-on-migrate: true

  cloud.stream:
    bindings:
      contactsBinding:
        binder: kBind1
        destination: finalAbstract
    binders:
      kBind1:
        type: kstream
        environment:
          spring.cloud.stream.kafka.streams.binder:
            brokers: localhost:9092

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwerty
    hikari:
      poolName: Hikari
      auto-commit: false
      connection-timeout: 20000
      maximum-pool-size: 5



