spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  flyway:
#    migrate-at-start: true
#    baseline-on-migrate: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SPRING_DATASOURCE_URL:'jdbc:postgresql://localhost:5432/postgres'}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:qwerty}
    hikari:
      poolName: Hikari
      auto-commit: false
      connection-timeout: 20000
      maximum-pool-size: 5



