version: '3.8'
services:

  zookeeper:
    image: debezium/zookeeper
    ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888
#    networks:
#      - debezium_network

  kafka:
    image: debezium/kafka
    ports:
    - 9092:9092
    links:
    - zookeeper
    environment:
    - ZOOKEEPER_CONNECT=zookeeper:2181
#    networks:
#      - debezium_network

  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
              connect:
                url: "http://connect-debezium-postgresql:8083"
    ports:
      - 8888:8080
#    networks:
#      - debezium_network

  postgres:
    image: debezium/postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DATABASE=postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - 5050:80

  connect-debezium-postgresql:
    image: debezium/connect
    restart: always
    ports:
      - 8083:8083
#      - 5005:5005
    links:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses
      - CONNECTOR_CLASS='io.debezium.connector.postgresql.PostgresConnector'
      - TASKS_MAX=1
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=qwerty
      - DATABASE_DBNAME=postgres
      - DATABASE_SERVER_NAME=postgres1
      - DATABASE_WHITELIST=postgres
      - TABLE_WHITELIST=public.contact
      - DATABASE_HISTORY_KAFKA_BOOTSTRA_SERVERS=kafka:9092
      - DATABASE_HISTORY_KAFKA_TOPIC=schema-changes.test_db
      - TRANSFORMS=route
      - TRANSFORMS_ROUTE_TYPE=org.apache.kafka.connect.transforms.RegexRouter
      - TRANSFORMS_ROUTE_REGEX=([^.]+)\\.([^.]+)\\.([^.]+)
      - TRANSFORMS_ROUTE_REPLACEMENT=$$3


#    networks:
#      - debezium_network


#networks:
#  debezium_network:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.170.53.0/24